version: 2.1
orbs:
  snyk: snyk/snyk@1.0.1
jobs:
  build:
    docker:
      - image: 'python:1.8-slim-buster'
    steps:
      - checkout
      - run: pip3 install requirements.txt
      - snyk/scan
workflows: null
