version: 2.1
orbs:
  snyk: snyk/snyk@1.0.1
jobs:
  build:
    docker:
      - image: 'caf3ina/vulnerableimage'
    steps:
      - checkout
      - run: pip3 install requirements.txt
      - snyk/scan
